image: php:8.1

stages:
    - test
    - deploy

test:
    stage: test
    tags:
        - build
    script:
        - php artisan test
    
deploy:
    stage: deploy
    tags:
        - build
    script:
        - echo "deploying"