version: '3.8'

services:
    nginx:
        image: nginx
        container_name: samgau_nginx
        restart: always
        working_dir: /var/www/samgau/
        volumes:
            - ./:/var/www/samgau
            - ./docker/nginx/:/etc/nginx/conf.d
        ports:
            - 83:80

    php:
        container_name: samgau_php
        restart: always
        working_dir: /var/www/samgau/
        build:
            context: docker/php
            dockerfile: Dockerfile
        user: ${UID}:${GID}
        volumes:
            - ./:/var/www/samgau
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
        ports:
            - 9003:9000

    postgres:
        container_name: samgau_postgres
        restart: always
        image: postgres:14
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes:
            - samgau-postgres:/data/postgres
        ports:
            - 5433:5432

volumes:
    samgau-postgres:
        external: true
